### ISSUE TITLE
What video codec is used in the project ?

### ISSUE THREAD

**Issue by balajiraghuram92** [arktronic/cameraserve#2]
Hi,
what video codec is used in this project for webcam streaming, there is good lag when streaming though WiFi LAN.

Can you at-least point out in which script you have mentioned the Codec so i can view the code.

Any suggestions on reducing latency on the live webcam streaming if possible.

Sorry for putting the Question as an issue,could not find a email for the query.

Kindly waiting for your reply.

Thank You.

**Comment by arktronic** [comment]
This app is using MJPEG, which is more of a pseudo-codec than anything else. It's essentially a series of JPEG images streamed over HTTP. You can see this [here](https://github.com/arktronic/cameraserve/blob/13897cbe9ba516700a4700e30734bb2e252672a5/app/src/main/java/com/arkconcepts/cameraserve/MjpegSocket.java).

I've not measured latency, but from informal testing, it seems decent, although it is highly dependent on the hardware.
