### ISSUE TITLE
Local network

### ISSUE THREAD

**Issue by shaniceweiwei** [arktronic/cameraserve#4]
My project actually only need the camera to stream in local network regardlessly the Internet speed, just to remotely see one android to another android's camera in the same area same network. Currently with this code, its smooth in some area, and it wasn't in different area which has poor internet connection. How can i modify the code not to went through Internet? I'm sorry, I'm new to this field.

**Comment by arktronic** [comment]
This application doesn't require an Internet connection, nor does it use any Internet resources by default. In fact, it is actively discouraged to connect to it via the Internet because of security concerns.

**Comment by shaniceweiwei** [comment]
> This application doesn't require an Internet connection, nor does it use any Internet resources by default. In fact, it is actively discouraged to connect to it via the Internet because of security concerns.

but why then its slow in some other area with weak Internet connection if it doesnt gone thru Internet? i've even connected both devices to my mobile hotspot in the same area, much more slower compared when im connecting in my home's Wifi.

**Comment by arktronic** [comment]
It could be any number of factors relating to your Wi-Fi or phone's configuration and capabilities. Regardless, this project does not itself use Internet services for any kind of image transmission.
